config/routes.rb
Rails.application.routes.draw do

  resources :teams do
    resources :players
  end

  root 'teams#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, presence: true
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_team
  before_action :set_player, only: [:show, :destroy, :edit, :update]

  def index
    @players = @team.players.all
  end

  def show
  end

  def new
    @player = Player.new
  end

  def create
    @player = @team.players.build(player_params)
    if @player.save
      flash[:success] = "#{@player.name} was successfully added to the #{@team.name}"
      redirect_to team_player_path(@team, @player)
    else
      render 'new'
    end
  end

  def destroy
    name = @player.name
    @player.destroy
    flash[:success] = "#{name} was deleted!"
    redirect_to team_players_path(@team)
  end

  def edit
  end

  def update
    if @player.update_attributes(player_params)
      flash[:success] = "#{@player.name} info updated!"
      redirect_to team_player_path(@team, @player)
    else
      render 'edit'
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :number, :position)
  end

  def set_team
    @team = Team.find(params[:team_id])
  end

  def set_player
    @player = @team.players.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def show
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to @team
      flash[:notice] = "#{@team.name} was successfully created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @team.update_attributes(team_params)
      flash[:success] = "Team info updated!"
      redirect_to @team
    else
      render 'edit'
    end
  end

  def destroy
    name = @team.name
    @team.destroy
    flash[:success] = "#{name} was deleted!"
    redirect_to teams_path
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name, :sport)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResourcesPracticeApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_for [@team, @player] do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/players/edit.html.erb
<h1>Edit info for <%= @player.name %></h1>

<%= render 'form' %>

app/views/players/index.html.erb
<h1>Roster for <%= @team.name %></h1>
<%= link_to 'Add player to roster', new_team_player_path %> |
<%= link_to 'Teams', teams_path %>

<p></p>

<table>
  <tr>
    <th>NAME</th>
    <th>NUMBER</th>
    <th>POSITION</th>
    <th></th>
  </tr>
  <% @players.each do |player| %>
    <tr>
      <td><p><%= player.name %></p></td>
      <td><p><%= player.number %></p></td>
      <td><p><%= player.position %></p></td>
      <td><p><%= link_to 'View', team_player_path(@team, player) %></p></td>
    </tr>
  <% end %>
</table>

app/views/players/new.html.erb
<h1>Add new player to the <%= @team.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', team_players_path(@team, @player) %> |
<%= link_to 'Teams List', teams_path %>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>

<p><strong>Team:</strong> <%= @team.name %></p>
<p><strong>Position:</strong> <%= @player.position %></p>
<p><strong>Number:</strong> <%= @player.number %></p>

<%= link_to 'Back', team_players_path(@team, @player) %> |
<%= link_to 'Edit', edit_team_player_path(@team, @player) %> |
<%= link_to 'Delete', team_player_path(@team, @player), method: :delete, data: { confirm: 'Are you sure?' } %>